#+BEGIN_HTML
---
layout: page
title: "Masataro Asai"
date: 2014-01-17 00:24
comments: true
sharing: true
footer: true
---
#+END_HTML
# Local Variables:
# octopress-export-org-to-md: page
# End:

mailto:guicho2.71828-at-gmail.com

+ Doctoral Student at University of Tokyo.
  + Department of General Systems Studies, Graduate School of Arts and Sciences.
+ My advisor is [[http://metahack.org/][Alex Fukunaga]].
+ Research Interest : Artificial Intelligence, Automated Planning and Scheduling, Heuristic Search.
  + See [[../publications/][Publications]] for more details.
+ [[./asai-cv.pdf][CV]]

** Past Interests

I received B.Eng. from the Faculty of Engineering, University of Tokyo.
I was in [[http://save.sys.t.u-tokyo.ac.jp/index_e.html][Yoshimura & Izmi Lab]], whose members are mainly interested in FEM/MPS and /Traffic Simulation/.

My graduate thesis was about using stochastic 2D agents for generating
the cooperative behaviors in the traffic simulation. (The paper is in
Japanese, so I do not make it public here.)

** Hobby / Personal Activity

+ Programming Language and Common Lisp
+ Electric circuits and Microcontroller
  + I have worked on a bipedal robot in the past
+ [[../gallery/][DIY modification of internal combustion engine]]
+ [[../gallery/][Car, Driving, Gymkhana]]
+ [[http://runkeeper.com/user/941210962/profile][Road racers (bicycles)]] --- recently stolen. Cursing the thief as hell.
+ FPGA wannabe.


